version: '3'
services:
  front:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: yarn start
    env_file:
      - .env.prod
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
    external: true
