version: '3'
services:
  front:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: yarn dev
    volumes:
      - .:/workdir
      - ignore:/workdir/node_modules
    working_dir: /workdir
    env_file:
      - .env
    networks:
      - blog-network

volumes:
  ignore:

networks:
  blog-network:
    driver: bridge
    external: true
